name: Terraform Azure Infrastructure Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'IaC/**'

env:
  TF_WORKING_DIR: ./IaC

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -var="sql_admin_login=${{ secrets.SQL_ADMIN_LOGIN }}" -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" -var="my_ip_address=${{ secrets.MY_IP_ADDRESS }}"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve -var="sql_admin_login=${{ secrets.SQL_ADMIN_LOGIN }}" -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" -var="my_ip_address=${{ secrets.MY_IP_ADDRESS }}"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

