name: Terraform Azure Infrastructure Deployment

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'IaC/**'
      - '.github/workflows/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-${{ github.ref }}
      cancel-in-progress: true
    env:
      TF_WORKING_DIR: ./IaC
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Azure Login (service principal)
          uses: azure/login@v2
          with:
            auth-type: 'service_principal'
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

        - name: Terraform Fmt
          working-directory: ${{ env.TF_WORKING_DIR }}
          run: terraform fmt -recursive -check -diff

        - name: Terraform Validate
          working-directory: ${{ env.TF_WORKING_DIR }}
          run: terraform validate

        - name: Terraform Init
          working-directory: ${{ env.TF_WORKING_DIR }}
          run: terraform init -reconfigure

        - name: Terraform Plan
          working-directory: ${{ env.TF_WORKING_DIR }}
          run: terraform plan -var="sql_admin_login=${{ secrets.SQL_ADMIN_LOGIN }}" -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" -var="my_ip_address=${{ secrets.MY_IP_ADDRESS }}"

        - name: Terraform Apply
          if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
          working-directory: ${{ env.TF_WORKING_DIR }}
          run: terraform apply -auto-approve -var="sql_admin_login=${{ secrets.SQL_ADMIN_LOGIN }}" -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" -var="my_ip_address=${{ secrets.MY_IP_ADDRESS }}"
